language: java
jdk: oraclejdk8

install: true

before_install:
- wget http://services.gradle.org/distributions/gradle-4.10.2-bin.zip
- unzip -qq gradle-4.10.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-4.10.2
- export PATH=$GRADLE_HOME/bin:$PATH

script:
- gradle assemble
- gradle check

notifications:
  email: false